# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
#   - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
#   - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
#   - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
#   - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
# language: python
# python:
#   - "3.4"
# install:
#   - "pip install hitch"
#   - "cd tests"
#   - "hitch init"
# script:
#   - "hitch test . --extra '{\"xvfb\":true, \"pause_on_failure\":false}'"

language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
- pypy3
env:
- DJANGO=1.4.15
- DJANGO=1.6.7
- DJANGO=1.7
install:
- pip install -q gitversion
- pip install -q Django==$DJANGO
- pip install -q .
- pip install -q coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 3.2
    env: DJANGO=1.4.15
  - python: 3.3
    env: DJANGO=1.4.15
  - python: pypy3
    env: DJANGO=1.4.15
deploy:
  provider: pypi
  user: LeaChim
  password:
    secure: IuIoDvmYRKjnQQ9wYSPSfKDgG/+8/nDqTj3KUacHt8XCKbjVcbKxsPKz76Zr214iVTqDQUt35w7wIENJSYP0LaHQ42TekwF+TtDcifSzgvQpxyJ0sP9IjqNHaJ6oHa/XXJJWWQjypFLOOUDSMW8t6+dKcrQp/vHctHvVbP1gECA=
  distributions: "bdist_wheel sdist"
  on:
    all_branches: true
    repo: founders4schools/django-donations
    tags: true
    condition: "$DJANGO = 1.7"
