language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO=1.8
  - DJANGO=1.9
#  - DJANGO=1.10

install:
  - pip install -q Django==$DJANGO
  - pip install -q .
  - pip install -q coveralls

script:
  - python setup.py test

after_success:
  - coveralls

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9
#    - python: 3.3
#      env: DJANGO=1.10
#  allowed_failures:
#    - env: DJANGO=1.10  # Due to django-autoconfig

notifications:
  slack:
    rooms:
      - f4s:u17h2Cc7RhhHNtypnAu7jbgY#dev
    on_success: change
    on_failure: always
  email: false

deploy:
  provider: pypi
  user: nanorepublica
  distributions: bdist_wheel sdist
  on:
    branch: master
    repo: founders4schools/django-donations
    tags: true
  password:
    secure: OuIJEdY2eJQSsqI6UlaJhytO6NJlcY7RPBjo/mbMNHKfdabdlsb7c2FnoIhzz8Bmh07HXbBTVEUgplpcAjftc3p0O4QL8neiwmmfOhmbwpZaxSI5D28k7v3ST8bTIwotl2v97z9lvbg8xqlpKdnTO+KnaYAsXeNMC2GgQErwUB5jYjRR+4F4wwaIKFwYjraKkHPAe40vHM5kpn3bI1X59udun264O22PrvmVa9L6ilr0lM8leHLmznWzvYVryxh90sh29tFtqo04zSdxpERS0PBWYshHYFEydn5dt2uIj9Ea54MU+Q+2d5sPcKNPFn/Zsg+JDetcB9eSXLng+iSMCDZt6sHVxg6XMyycCcgP9ct//SpQZE+V3F0+IiLhm8Ra2aWS7VMy0aCjgQwnOLijWygESIJFG5u84Df7msryMqf3wA7Nnj1tmJinFabbVxqSqkjtskkbPgt6Uf0RcKZdg/YtLiDstfFmfaIcpKF9t5+f0/k8OQtRS9m7+pWYv6+zUS9v2ijctUlt+3umlX6ilw9uZoqi/efmSyPTp6i4/q3LypqiTO8hS11vqfFFRpTXM+nSw/I2jHYjlfy46/kiK5OW98lb2cMJ5iLF8mcUea2aMi5gcPL/70Z80p5/CWRLn1CtRULUtRtk8MUvuMRR75shaB/rW+tpipWQZIRUW7I=
